/*
각 세대별 자식이 없는 개체의 수(COUNT)와 세대(GENERATION)를 출력하는 SQL문을 작성해주세요. 
이때 결과는 세대에 대해 오름차순 정렬해주세요. 
단, 모든 세대에는 자식이 없는 개체가 적어도 1개체는 존재합니다.
*/
WITH RECURSIVE GEN AS 
    (SELECT E1.ID, E2.ID AS CHILD, 1 AS GENERATION
    FROM ECOLI_DATA AS E1
    LEFT OUTER JOIN ECOLI_DATA AS E2
    ON E1.ID = E2.PARENT_ID 
    WHERE E1.PARENT_ID IS NULL
    
    UNION ALL
     
    SELECT GEN.CHILD AS ID, E3.ID AS CHILD, GENERATION + 1 AS GENERATION
    FROM GEN
    LEFT OUTER JOIN ECOLI_DATA AS E3
    ON GEN.CHILD = E3.PARENT_ID
    WHERE GEN.CHILD IS NOT NULL)

SELECT COUNT(*) AS COUNT, GENERATION
FROM GEN
WHERE CHILD IS NULL
GROUP BY GENERATION;